# ServiceAccount for Dashboard

apiVersion: v1
kind: ServiceAccount
metadata:
  name: dashboard-sa
  namespace: dashboard
  labels:
    app.kubernetes.io/name:      dashboard
    app.kubernetes.io/component: serviceaccount
automountServiceAccountToken: false
