# Secret for Dashboard (Admin Dashboard)

apiVersion: v1
kind: Secret
metadata:
  name: dashboard-secret
  namespace: dashboard
  labels:
    app.kubernetes.io/name:      dashboard
    app.kubernetes.io/component: secret
type: Opaque
data: {}
